### ISSUE TITLE
CI build fails

### ISSUE THREAD

**Issue by jonno85uk** [jonno85uk/chestnut#64]
The build step of chestnut in circleci fails. It is due to the use of std::optional which is a c++17 feature. gcc in Ubuntu18.04 (of which the CI image is) does not support c++17.

**Comment by jonno85uk** [comment]
A Ubuntu-19.04 image exists in circle-ci. The build now fails due to a sonar-scanner execution failure.

**Comment by jonno85uk** [comment]
SonarSource/SonarJS#1110

**Comment by jonno85uk** [comment]
> java.lang.NullPointerException
>         at com.sonar.cpp.analyzer.ClangDriver.envListToMap(ClangDriver.java:508)
>         at com.sonar.cpp.analyzer.ClangDriver.lambda$probeCompiler$7(ClangDriver.java:499)
>         at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1138)
>         at com.sonar.cpp.analyzer.ClangDriver.probeCompiler(ClangDriver.java:497)
>         at com.sonar.cpp.analyzer.ClangDriver.onCapture(ClangDriver.java:320)
>         at com.sonar.cpp.plugin.CFamilySensor.process(CFamilySensor.java:294)
>         at com.sonar.cpp.plugin.CFamilySensor.execute(CFamilySensor.java:206)
>         at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:48)
>         at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:85)
>         at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:62)
>         at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:82)
>         at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
>         at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
>         at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:403)
>         at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:399)
>         at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:362)
>         at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
>         at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
>         at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:141)
>         at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
>         at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
>         at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:72)
>         at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:66)
>         at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.base/java.lang.reflect.Method.invoke(Method.java:564)
>         at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
>         at com.sun.proxy.$Proxy0.execute(Unknown Source)
>         at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:185)
>         at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:137)
>         at org.sonarsource.scanner.cli.Main.execute(Main.java:112)
>         at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
>         at org.sonarsource.scanner.cli.Main.main(Main.java:61)
>

**Comment by jonno85uk** [comment]
Now using codacy instead of sonarqube
